'use client';

import { useState } from 'react';
import { FileText, Printer, Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';

export interface ReportSection {
  title: string;
  content: React.ReactNode;
  printable?: boolean;  // Whether to include in print output
}

interface ReportExportProps {
  reportTitle: string;
  symbol?: string;
  sections: ReportSection[];
  className?: string;
}

/**
 * Report export component.
 *
 * Uses browser window.print() with a print stylesheet for PDF generation.
 * No third-party PDF library required — the browser handles rendering.
 */
export function ReportExport({
  reportTitle,
  symbol,
  sections,
  className,
}: ReportExportProps) {
  const [isPrinting, setIsPrinting] = useState(false);

  const handlePrint = () => {
    setIsPrinting(true);
    // Allow state update to render before opening print dialog
    setTimeout(() => {
      window.print();
      setIsPrinting(false);
    }, 200);
  };

  const handleCopyMarkdown = async () => {
    const lines: string[] = [
      `# ${reportTitle}`,
      symbol ? `**Symbol:** ${symbol}` : '',
      `**Generated:** ${new Date().toLocaleDateString()}`,
      '',
      '---',
      '',
    ];

    for (const section of sections) {
      lines.push(`## ${section.title}`, '');
      lines.push('*See report for detailed data.*', '');
    }

    await navigator.clipboard.writeText(lines.join('\n'));
  };

  return (
    <div className={cn('space-y-4', className)}>
      {/* Export buttons */}
      <div className="flex flex-wrap items-center gap-2">
        <Button
          variant="outline"
          size="sm"
          onClick={handlePrint}
          disabled={isPrinting}
          className="gap-1.5"
        >
          <Printer className="h-3.5 w-3.5" />
          {isPrinting ? 'Opening…' : 'Print / Save PDF'}
        </Button>
        <Button
          variant="ghost"
          size="sm"
          onClick={handleCopyMarkdown}
          className="gap-1.5"
        >
          <Download className="h-3.5 w-3.5" />
          Copy as Markdown
        </Button>
      </div>

      {/* Print-only header (hidden on screen, visible when printing) */}
      <div className="hidden print:block print:mb-6">
        <h1 className="text-2xl font-bold">{reportTitle}</h1>
        {symbol && <p className="text-lg text-gray-600">Symbol: {symbol}</p>}
        <p className="text-sm text-gray-400">
          Generated {new Date().toLocaleDateString()} &middot; Smart Strategies Builder
        </p>
        <hr className="my-4" />
      </div>

      {/* Report sections */}
      <div className="space-y-6">
        {sections.map((section, i) => (
          <div
            key={i}
            className={cn(
              'rounded-lg border bg-card',
              section.printable === false && 'print:hidden'
            )}
          >
            <div className="flex items-center gap-2 border-b px-5 py-3">
              <FileText className="h-4 w-4 text-muted-foreground" />
              <h3 className="font-semibold text-sm">{section.title}</h3>
            </div>
            <div className="p-5">{section.content}</div>
          </div>
        ))}
      </div>

      {/* Print disclaimer */}
      <div className="hidden print:block print:mt-8 print:border-t print:pt-4">
        <p className="text-xs text-gray-400">
          This report is generated by Smart Strategies Builder for educational and
          analytical purposes only. It does not constitute investment advice, a
          solicitation, or an offer to buy or sell any security. Past performance and
          analytical models are not indicators of future results. Always consult a
          qualified financial adviser before making investment decisions.
        </p>
      </div>
    </div>
  );
}
